# -*- coding: utf-8 -*-
"""
@software: PyCharm
@file: airline_information.py
@time: 2020年10月16日22:11:22
@Desc：航线详细信息界面的基本结构
"""
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("MainWindow")
        Dialog.resize(530, 553)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 110, 71, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stime = QtWidgets.QLabel(self.centralwidget)
        self.stime.setGeometry(QtCore.QRect(20, 180, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.stime.setFont(font)
        self.stime.setObjectName("stime")
        self.etime = QtWidgets.QLabel(self.centralwidget)
        self.etime.setGeometry(QtCore.QRect(340, 180, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.etime.setFont(font)
        self.etime.setObjectName("etime")
        self.sairport = QtWidgets.QLabel(self.centralwidget)
        self.sairport.setGeometry(QtCore.QRect(20, 300, 161, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.sairport.setFont(font)
        self.sairport.setObjectName("sairport")
        self.eairport = QtWidgets.QLabel(self.centralwidget)
        self.eairport.setGeometry(QtCore.QRect(350, 300, 161, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.eairport.setFont(font)
        self.eairport.setObjectName("eairport")
        self.week1 = QtWidgets.QLabel(self.centralwidget)
        self.week1.setGeometry(QtCore.QRect(220, 200, 171, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.week1.setFont(font)
        self.week1.setObjectName("week1")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(140, 450, 71, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 450, 81, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(210, 210, 121, 81))
        font = QtGui.QFont()
        font.setFamily("交通标志专用字体")
        font.setPointSize(72)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.scity = QtWidgets.QLabel(self.centralwidget)
        self.scity.setGeometry(QtCore.QRect(20, 240, 201, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.scity.setFont(font)
        self.scity.setObjectName("scity")
        self.ecity = QtWidgets.QLabel(self.centralwidget)
        self.ecity.setGeometry(QtCore.QRect(340, 240, 191, 61))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.ecity.setFont(font)
        self.ecity.setObjectName("ecity")
        self.punrate = QtWidgets.QLabel(self.centralwidget)
        self.punrate.setGeometry(QtCore.QRect(130, 380, 120, 71))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.punrate.setFont(font)
        self.punrate.setObjectName("punrate")
        self.price = QtWidgets.QLabel(self.centralwidget)
        self.price.setGeometry(QtCore.QRect(250, 380, 250, 71))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.price.setFont(font)
        self.price.setObjectName("price")
        self.week2 = QtWidgets.QLabel(self.centralwidget)
        self.week2.setGeometry(QtCore.QRect(220, 280, 280, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.week2.setFont(font)
        self.week2.setObjectName("week2")
        self.id = QtWidgets.QLabel(self.centralwidget)
        self.id.setGeometry(QtCore.QRect(230, 40, 171, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(36)
        self.id.setFont(font)
        self.id.setObjectName("id")
        self.no = QtWidgets.QLabel(self.centralwidget)
        self.no.setGeometry(QtCore.QRect(230, 100, 181, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(36)
        self.no.setFont(font)
        self.no.setObjectName("no")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 330, 501, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 170, 501, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(90, 370, 381, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(90, 490, 381, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(80, 380, 16, 121))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(460, 380, 16, 121))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        # Dialog.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(Dialog)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 26))
        # self.menubar.setObjectName("menubar")
        # Dialog.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(Dialog)
        # self.statusbar.setObjectName("statusbar")
        # Dialog.setStatusBar(self.statusbar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("MainWindow", "航班详细信息"))
        self.label.setText(_translate("MainWindow", "航班编号"))
        self.label_2.setText(_translate("MainWindow", "航班号"))
        self.stime.setText(_translate("MainWindow", "11:00"))
        self.etime.setText(_translate("MainWindow", "12:00"))
        self.sairport.setText(_translate("MainWindow", "新郑国际机场"))
        self.eairport.setText(_translate("MainWindow", "北京大兴机场"))
        self.week1.setText(_translate("MainWindow", "一 二 三 四"))
        self.label_9.setText(_translate("MainWindow", "准点率"))
        self.label_10.setText(_translate("MainWindow", "价  格"))
        self.label_11.setText(_translate("MainWindow", "→"))
        self.scity.setText(_translate("MainWindow", "郑州"))
        self.ecity.setText(_translate("MainWindow", "北京"))
        self.punrate.setText(_translate("MainWindow", "98%"))
        self.price.setText(_translate("MainWindow", "680起"))
        self.week2.setText(_translate("MainWindow", "五 六 七"))
        self.id.setText(_translate("MainWindow", "22981"))
        self.no.setText(_translate("MainWindow", "CZ3907"))

