# -*- coding: utf-8 -*-
"""
@software: PyCharm
@file: DAP.py
@time: 2020年10月17日08:33:20
@Desc：平台界面的基本结构
"""

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.allWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.allWidget.setGeometry(QtCore.QRect(0, 0, 1441, 741))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(16)
        self.allWidget.setFont(font)
        self.allWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.allWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.allWidget.setIconSize(QtCore.QSize(20, 20))
        self.allWidget.setElideMode(QtCore.Qt.ElideNone)
        self.allWidget.setUsesScrollButtons(True)
        self.allWidget.setDocumentMode(False)
        self.allWidget.setObjectName("allWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.peopleWidget = QtWidgets.QTabWidget(self.tab)
        self.peopleWidget.setGeometry(QtCore.QRect(0, 0, 1441, 711))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.peopleWidget.setFont(font)
        self.peopleWidget.setObjectName("peopleWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.peopleBox = QtWidgets.QComboBox(self.tab_3)
        self.peopleBox.setGeometry(QtCore.QRect(10, 10, 221, 41))
        self.peopleBox.setObjectName("peopleBox")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(280, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.peopleList = QtWidgets.QTableWidget(self.tab_3)
        self.peopleList.setGeometry(QtCore.QRect(10, 70, 1411, 560))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.peopleList.setFont(font)
        self.peopleList.setObjectName("peopleList")
        self.peopleList.setColumnCount(0)
        self.peopleList.setRowCount(0)
        self.peopleWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1431, 681))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.allChart = QtWidgets.QFrame(self.gridLayoutWidget)
        self.allChart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.allChart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.allChart.setObjectName("allChart")
        self.chart1 = QtWidgets.QWidget(self.allChart)
        self.chart1.setEnabled(True)
        self.chart1.setGeometry(QtCore.QRect(0, 0, 471, 321))
        self.chart1.setObjectName("chart1")
        self.chart4 = QtWidgets.QWidget(self.allChart)
        self.chart4.setGeometry(QtCore.QRect(0, 320, 471, 341))
        self.chart4.setObjectName("chart4")
        self.chart2 = QtWidgets.QWidget(self.allChart)
        self.chart2.setGeometry(QtCore.QRect(470, 0, 481, 321))
        self.chart2.setObjectName("chart2")
        self.chart3 = QtWidgets.QWidget(self.allChart)
        self.chart3.setGeometry(QtCore.QRect(950, 0, 481, 321))
        self.chart3.setObjectName("chart3")
        self.chart5 = QtWidgets.QWidget(self.allChart)
        self.chart5.setGeometry(QtCore.QRect(470, 320, 481, 331))
        self.chart5.setObjectName("chart5")
        self.chart6 = QtWidgets.QWidget(self.allChart)
        self.chart6.setGeometry(QtCore.QRect(950, 320, 481, 331))
        self.chart6.setObjectName("chart6")
        self.gridLayout.addWidget(self.allChart, 0, 0, 1, 1)
        self.peopleWidget.addTab(self.tab_4, "")
        self.allWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.airlineWidget = QtWidgets.QTabWidget(self.tab_2)
        self.airlineWidget.setGeometry(QtCore.QRect(0, 0, 1441, 721))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.airlineWidget.setFont(font)
        self.airlineWidget.setObjectName("airlineWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.airlineChart = QtWidgets.QWidget(self.tab_5)
        self.airlineChart.setGeometry(QtCore.QRect(0, 0, 1431, 661))
        self.airlineChart.setObjectName("airlineChart")
        self.airlineWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label = QtWidgets.QLabel(self.tab_6)
        self.label.setGeometry(QtCore.QRect(30, 40, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.scityBox = QtWidgets.QComboBox(self.tab_6)
        self.scityBox.setGeometry(QtCore.QRect(70, 40, 131, 31))
        self.scityBox.setObjectName("scityBox")
        self.label_2 = QtWidgets.QLabel(self.tab_6)
        self.label_2.setGeometry(QtCore.QRect(220, 40, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ecityBox = QtWidgets.QComboBox(self.tab_6)
        self.ecityBox.setGeometry(QtCore.QRect(270, 41, 131, 31))
        self.ecityBox.setObjectName("ecityBox")
        self.queryButton1 = QtWidgets.QPushButton(self.tab_6)
        self.queryButton1.setGeometry(QtCore.QRect(480, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.queryButton1.setFont(font)
        self.queryButton1.setObjectName("queryButton1")
        self.airLineWidget1 = QtWidgets.QTableWidget(self.tab_6)
        self.airLineWidget1.setGeometry(QtCore.QRect(20, 90, 601, 581))
        self.airLineWidget1.setObjectName("airLineWidget1")
        self.label_3 = QtWidgets.QLabel(self.tab_6)
        self.label_3.setGeometry(QtCore.QRect(800, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_4.setGeometry(QtCore.QRect(930, 40, 300, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.queryButton2 = QtWidgets.QPushButton(self.tab_6)
        self.queryButton2.setGeometry(QtCore.QRect(1260, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.queryButton2.setFont(font)
        self.queryButton2.setObjectName("queryButton2")
        self.airLineWidget2 = QtWidgets.QTableWidget(self.tab_6)
        self.airLineWidget2.setGeometry(QtCore.QRect(800, 90, 601, 581))
        self.airLineWidget2.setObjectName("airLineWidget2")
        self.airlineWidget.addTab(self.tab_6, "")
        self.allWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionasd = QtWidgets.QAction(MainWindow)
        self.actionasd.setObjectName("actionasd")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.actionasd)
        self.menu.addAction(self.action)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.allWidget.setCurrentIndex(0)
        self.peopleWidget.setCurrentIndex(0)
        self.airlineWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "航空公司数据处理平台"))
        self.pushButton.setText(_translate("MainWindow", "查看"))
        self.peopleWidget.setTabText(self.peopleWidget.indexOf(self.tab_3), _translate("MainWindow", "用户查询"))
        self.peopleWidget.setTabText(self.peopleWidget.indexOf(self.tab_4), _translate("MainWindow", "可视化分析"))
        self.allWidget.setTabText(self.allWidget.indexOf(self.tab), _translate("MainWindow", "客户价值"))
        self.airlineWidget.setTabText(self.airlineWidget.indexOf(self.tab_5), _translate("MainWindow", "航线图"))
        self.label.setText(_translate("MainWindow", "从"))
        self.label_2.setText(_translate("MainWindow", "到"))
        self.queryButton1.setText(_translate("MainWindow", "查询"))
        self.label_3.setText(_translate("MainWindow", "航班名称"))
        self.queryButton2.setText(_translate("MainWindow", "查询"))
        self.airlineWidget.setTabText(self.airlineWidget.indexOf(self.tab_6), _translate("MainWindow", "航班查询"))
        self.allWidget.setTabText(self.allWidget.indexOf(self.tab_2), _translate("MainWindow", "航线规划"))
        self.menu.setTitle(_translate("MainWindow", "客户价值分析"))
        self.menu_2.setTitle(_translate("MainWindow", "航线规划"))
        self.actionasd.setText(_translate("MainWindow", "用户查询"))
        self.action.setText(_translate("MainWindow", "可视化分析"))
        self.action_2.setText(_translate("MainWindow", "航线图"))
        self.action_3.setText(_translate("MainWindow", "航班查询"))

